My changes
pisilinux/piksemel pull request #3
Opened 2022-03-26 15:56 UTC by eersoy93

- Update README.md
- Fix tests
- Fix compiler warnings

2022-03-26 17:13 UTC, safaariman requested changes

2022-03-26 17:13 UTC, safaariman commented on README.md
> +# Piksemel 2.0 (eersoy93's fork)
Bu değişikliği geri almanı rica edeceğim.

2022-03-28 07:13 UTC, eersoy93 commented on README.md
> +# Piksemel 2.0 (eersoy93's fork)
Tabii ki geri alacağım, gözümden kaçmış.

Önceden amacım Piksemel'i forklamaktı, bu yüzden kendim ayrı bir sürüm oluşturacaktım. Ancak şimdiki organizasyonu oluşturma amacım Pisi'ye katkıda bulunmak. Düzeltmeyi yaparken unutmuşum, özür dilerim bunun için.

Anlayışınız için teşekkür ederim.

2022-03-28 07:16 UTC, eersoy93 commented on README.md
> +# Piksemel 2.0 (eersoy93's fork)
Değişiklik geri alınmıştır.

Mailden yeni gördüm bu mesajı, değişiklik ondan biraz gecikti.

2022-03-28 07:34 UTC, safaariman approved these changes

2022-03-28 07:35 UTC, merged